kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/cuisongliu/drone-kube/

steps:
- name: build-drone-kube
  image: golang:1.10
  commands:
     - go get -v
     - go get -u golang.org/x/lint/golint
     - golint  -set_exit_status ./...
     - go build -a -ldflags '-extldflags "-static"' .
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

- name: test-pubsh-drone-kube
  image: plugins/docker:linux-amd64
  settings:
    repo: cuisongliu/drone-kube
    tags: drone-test
    username:
      from_secret: docker-hub-user
    dockerfile: Dockerfile
    password:
      from_secret: docker-hub-pass

- name: dryrun-drone-kube
  image: cuisongliu/drone-kube:drone-test
  commands:
    - drone-kube -h
    - env

- name: publish-drone-kube
  image: plugins/docker:linux-amd64
  settings:
    repo: cuisongliu/drone-kube
    tags: ${DRONE_TAG=latest}
    username:
      from_secret: docker-hub-user
    dockerfile: Dockerfile
    password:
      from_secret: docker-hub-pass
