kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/cuisongliu/drone-kube/

steps:
- name: build-drone-kube
  image: golang:1.11
  commands:
     - go get -v
     - go get -u golang.org/x/lint/golint
     - golint  -set_exit_status ./...
     - go build -v -a -tags netgo -o drone-kube
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

- name: dryrun-drone-kube
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    daemon_off: false
    dockerfile: Dockerfile
    dry_run: true
    repo: cuisongliu/drone-kube
    tags: latest

- name: publish-drone-kube
  image: plugins/docker:linux-amd64
  settings:
    repo: cuisongliu/drone-kube
    tags: ${DRONE_TAG=latest}
    username:
      from_secret: docker-hub-user
    dockerfile: Dockerfile
    password:
      from_secret: docker-hub-pass
